/**
 * redirect-generator.ts
 *
 * Generates redirect configuration files for various platforms:
 * - Next.js (next.config.js async redirects)
 * - Netlify (_redirects file)
 * - nginx (map block for nginx.conf)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { RedirectEntry, RedirectFormat } from "./types.js";

/**
 * Generate a Next.js redirects configuration block.
 *
 * Produces the `async redirects()` return value for next.config.js.
 */
export function generateNextJsRedirects(entries: RedirectEntry[]): string {
  if (entries.length === 0) {
    return "// No redirects to generate.\n";
  }

  const redirectObjects = entries.map((entry) => {
    const permanent = entry.statusCode === 301;
    return [
      "    {",
      `      source: "${entry.from}",`,
      `      destination: "${entry.to}",`,
      `      permanent: ${permanent},`,
      "    }",
    ].join("\n");
  });

  const lines = [
    "// Add this to your next.config.js (or next.config.mjs / next.config.ts)",
    "// Inside your config object:",
    "//",
    "// /** @type {import('next').NextConfig} */",
    "// const nextConfig = {",
    "//   async redirects() {",
    "//     return [",
    "//       ...generatedRedirects,",
    "//     ];",
    "//   },",
    "// };",
    "",
    "const generatedRedirects = [",
    redirectObjects.join(",\n"),
    "];",
    "",
    "module.exports = { generatedRedirects };",
    "",
  ];

  return lines.join("\n");
}

/**
 * Generate a Netlify _redirects file.
 *
 * Format: /old-path /new-path STATUS
 */
export function generateNetlifyRedirects(entries: RedirectEntry[]): string {
  if (entries.length === 0) {
    return "# No redirects to generate.\n";
  }

  const lines = [
    "# Generated by site-autofix",
    `# ${new Date().toISOString()}`,
    "#",
    "# Format: from  to  status",
    "#",
    ...entries.map(
      (entry) => `${entry.from}    ${entry.to}    ${entry.statusCode}`
    ),
    "",
  ];

  return lines.join("\n");
}

/**
 * Generate an nginx map block for use in nginx.conf.
 *
 * This produces a `map $uri $redirect_target` block that can be used
 * with an `if ($redirect_target)` directive.
 */
export function generateNginxRedirects(entries: RedirectEntry[]): string {
  if (entries.length === 0) {
    return "# No redirects to generate.\n";
  }

  const mapEntries = entries.map((entry) => {
    return `    ${entry.from}    ${entry.to};`;
  });

  const lines = [
    "# Generated by site-autofix",
    `# ${new Date().toISOString()}`,
    "#",
    "# Add this map block to the http {} context in nginx.conf,",
    "# then add the following to your server {} block:",
    "#",
    "#   if ($redirect_target) {",
    "#     return 301 $redirect_target;",
    "#   }",
    "#",
    "map $uri $redirect_target {",
    "    default \"\";",
    ...mapEntries,
    "}",
    "",
  ];

  return lines.join("\n");
}

/**
 * Generate redirect config content for the specified format.
 */
export function generateRedirects(
  entries: RedirectEntry[],
  format: RedirectFormat
): string {
  switch (format) {
    case "nextjs":
      return generateNextJsRedirects(entries);
    case "netlify":
      return generateNetlifyRedirects(entries);
    case "nginx":
      return generateNginxRedirects(entries);
    default: {
      const _exhaustive: never = format;
      throw new Error(`Unknown redirect format: ${String(_exhaustive)}`);
    }
  }
}

/**
 * Get the default filename for a redirect format.
 */
export function getRedirectFilename(format: RedirectFormat): string {
  switch (format) {
    case "nextjs":
      return "generated-redirects.js";
    case "netlify":
      return "_redirects";
    case "nginx":
      return "nginx-redirects.conf";
    default: {
      const _exhaustive: never = format;
      throw new Error(`Unknown redirect format: ${String(_exhaustive)}`);
    }
  }
}

/**
 * Write redirect config to disk.
 */
export function writeRedirectConfig(
  entries: RedirectEntry[],
  format: RedirectFormat,
  targetDir: string,
  filename?: string
): string {
  const content = generateRedirects(entries, format);
  const fname = filename ?? getRedirectFilename(format);
  const outputPath = path.join(targetDir, fname);

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, "utf-8");

  return outputPath;
}

/**
 * Write redirect configs for all supported formats.
 */
export function writeAllRedirectConfigs(
  entries: RedirectEntry[],
  targetDir: string
): string[] {
  const formats: RedirectFormat[] = ["nextjs", "netlify", "nginx"];
  const paths: string[] = [];

  for (const format of formats) {
    const outputPath = writeRedirectConfig(entries, format, targetDir);
    paths.push(outputPath);
  }

  return paths;
}
