import { describe, it, expect } from "vitest";
import {
  generateNextJsRedirects,
  generateNetlifyRedirects,
  generateNginxRedirects,
  generateRedirects,
} from "../src/redirect-generator.js";
import type { RedirectEntry } from "../src/types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function entry(from: string, to: string, statusCode: 301 | 302 = 301): RedirectEntry {
  return { from, to, statusCode };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("redirect-generator", () => {
  const singleEntry: RedirectEntry[] = [entry("/old", "/new")];
  const multipleEntries: RedirectEntry[] = [
    entry("/old-page", "/new-page"),
    entry("/blog/removed", "/blog/latest"),
    entry("/temp", "/permanent", 302),
  ];

  // -----------------------------------------------------------------------
  // Next.js redirect output format
  // -----------------------------------------------------------------------
  describe("generateNextJsRedirects()", () => {
    it("should produce valid Next.js redirects config", () => {
      const output = generateNextJsRedirects(singleEntry);

      expect(output).toContain("generatedRedirects");
      expect(output).toContain('source: "/old"');
      expect(output).toContain('destination: "/new"');
      expect(output).toContain("permanent: true");
    });

    it("should handle permanent=false for 302 status codes", () => {
      const entries = [entry("/temp", "/dest", 302)];
      const output = generateNextJsRedirects(entries);

      expect(output).toContain("permanent: false");
    });

    it("should return a comment for empty entries", () => {
      const output = generateNextJsRedirects([]);
      expect(output).toContain("No redirects to generate");
    });

    it("should include multiple redirect objects", () => {
      const output = generateNextJsRedirects(multipleEntries);

      expect(output).toContain('source: "/old-page"');
      expect(output).toContain('source: "/blog/removed"');
      expect(output).toContain('source: "/temp"');
      expect(output).toContain('destination: "/new-page"');
      expect(output).toContain('destination: "/blog/latest"');
      expect(output).toContain('destination: "/permanent"');
    });
  });

  // -----------------------------------------------------------------------
  // Netlify _redirects format
  // -----------------------------------------------------------------------
  describe("generateNetlifyRedirects()", () => {
    it("should produce lines in 'from  to  status' format", () => {
      const output = generateNetlifyRedirects(singleEntry);

      expect(output).toContain("/old");
      expect(output).toContain("/new");
      expect(output).toContain("301");
      // Verify the structure: from, to, status on the same line
      const dataLines = output
        .split("\n")
        .filter((l) => !l.startsWith("#") && l.trim().length > 0);
      expect(dataLines.length).toBe(1);
      expect(dataLines[0]).toMatch(/\/old\s+\/new\s+301/);
    });

    it("should include the site-autofix header comment", () => {
      const output = generateNetlifyRedirects(singleEntry);
      expect(output).toContain("Generated by site-autofix");
    });

    it("should return a comment for empty entries", () => {
      const output = generateNetlifyRedirects([]);
      expect(output).toContain("No redirects to generate");
    });

    it("should handle multiple entries", () => {
      const output = generateNetlifyRedirects(multipleEntries);

      const dataLines = output
        .split("\n")
        .filter((l) => !l.startsWith("#") && l.trim().length > 0);
      expect(dataLines.length).toBe(3);
      expect(dataLines[2]).toMatch(/\/temp\s+\/permanent\s+302/);
    });
  });

  // -----------------------------------------------------------------------
  // nginx map block format
  // -----------------------------------------------------------------------
  describe("generateNginxRedirects()", () => {
    it("should produce a map block with $uri and $redirect_target", () => {
      const output = generateNginxRedirects(singleEntry);

      expect(output).toContain("map $uri $redirect_target");
      expect(output).toContain('default ""');
      expect(output).toContain("/old");
      expect(output).toContain("/new;");
    });

    it("should include the header comment", () => {
      const output = generateNginxRedirects(singleEntry);
      expect(output).toContain("Generated by site-autofix");
    });

    it("should return a comment for empty entries", () => {
      const output = generateNginxRedirects([]);
      expect(output).toContain("No redirects to generate");
    });

    it("should contain all entries in the map block", () => {
      const output = generateNginxRedirects(multipleEntries);

      expect(output).toContain("/old-page");
      expect(output).toContain("/new-page;");
      expect(output).toContain("/blog/removed");
      expect(output).toContain("/blog/latest;");
      expect(output).toContain("/temp");
      expect(output).toContain("/permanent;");
    });
  });

  // -----------------------------------------------------------------------
  // generateRedirects() dispatcher
  // -----------------------------------------------------------------------
  describe("generateRedirects()", () => {
    it("should dispatch to Next.js generator", () => {
      const output = generateRedirects(singleEntry, "nextjs");
      expect(output).toContain("generatedRedirects");
    });

    it("should dispatch to Netlify generator", () => {
      const output = generateRedirects(singleEntry, "netlify");
      expect(output).toContain("Generated by site-autofix");
      expect(output).toMatch(/\/old\s+\/new\s+301/);
    });

    it("should dispatch to nginx generator", () => {
      const output = generateRedirects(singleEntry, "nginx");
      expect(output).toContain("map $uri $redirect_target");
    });
  });

  // -----------------------------------------------------------------------
  // Empty redirect list
  // -----------------------------------------------------------------------
  describe("empty redirect list", () => {
    it("should return a comment for each format", () => {
      for (const format of ["nextjs", "netlify", "nginx"] as const) {
        const output = generateRedirects([], format);
        expect(output).toContain("No redirects to generate");
      }
    });
  });
});
